name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, windows-latest, windows-11-arm64, ubuntu-latest, ubuntu-24.04-arm64]
        mode: [Pro, Lite]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: vultur/SmartEdu-Textbook
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: ${{ contains(matrix.os, 'arm64') && 'ARM64' || 'x64' }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run build script (${{ matrix.mode }})
        run: python ./src/deploy.py ${{ matrix.mode }}
        shell: bash
        env:
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/assets/*.zip
            ./dist/assets/*.dmg
            ./dist/assets/*.tar.gz
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
