name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm64, macos-latest, macos-15-intel, ubuntu-latest, ubuntu-24.04-arm64]
        mode: [lite, pro]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: vultur/SmartEdu-Tools
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: ${{ contains(matrix.os, 'arm64') && 'ARM64' || 'x64' }}

      - name: Install system dependencies (Linux Only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libegl1

      - name: Remove problematic libs (macOS Only)
        if: matrix.os == 'macos-15-intel'
        run: |
            brew remove --force --ignore-dependencies openssl@3
            brew cleanup openssl@3

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run deploy script
        run: python src/deploy.py ${{ matrix.mode }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          files: dist/assets/*.*
          overwrite_files: true
