name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        mode: [lite]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: vultur/SmartEdu-Tools
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: ${{ contains(matrix.os, 'arm64') && 'ARM64' || 'x64' }}

      - name: Install system dependencies (Linux Only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y --no-install-recommends \
          libegl1 libegl1-mesa libgl1 libgl1-mesa-glx libxcb1 libxcb-cursor0 libxcb-xinerama0 libxcb-icccm4 \
          libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 \
          libxcb-xkb1 libxkbcommon0 libxkbcommon-x11-0 libxcb-util1 libxcb-render0 \
          mesa-va-drivers mesa-vulkan-drivers libglx-mesa0 libgbm1 libdrm2 \
          libQt6Core.so.6 libQt6Gui.so.6 libQt6Widgets.so.6
        shell: bash

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run deploy script
        run: python ./src/deploy.py ${{ matrix.mode }}
        shell: bash
        env:
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./dist/assets/*.*
          file_glob: true
          repo_token: ${{ secrets.ACCESS_TOKEN }}
