name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, windows-latest, windows-11-arm64, ubuntu-latest, ubuntu-24.04-arm64]
        mode: [Pro, Lite]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: vultur/SmartEdu-Tools
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: ${{ contains(matrix.os, 'arm64') && 'ARM64' || 'x64' }}

      - name: Install system dependencies (Linux Only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y --no-install-recommends \
          libegl1 libopengl0 libgl1 libxcb1 libxcb-cursor0 libxcb-xinerama0 libxcb-icccm4 \
          libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 \
          libxcb-xkb1 libxkbcommon0 libxkbcommon-x11-0 libxcb-util1 libxcb-render0 \
          mesa-va-drivers mesa-vulkan-drivers libglx-mesa0 libgbm1 libdrm2
        shell: bash

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run deploy script
        run: python ./src/deploy.py ${{ matrix.mode }}
        shell: bash
        env:
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8
          QT_QPA_PLATFORM: offscreen

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: ./dist/assets/*.*
          allowUpdates: true
          removeArtifacts: true
          generateReleaseNotes: false
