name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        mode: [lite, pro]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: vultur/SmartEdu-Tools
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: ${{ contains(matrix.os, 'arm64') && 'ARM64' || 'x64' }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run deploy script
        run: python src/deploy.py ${{ matrix.mode }}
        env:
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          files: dist/assets/*.*
          overwrite_files: true
